### PR TITLE
Update tft.py

### PR DESCRIPTION
**Pull request by PsychoticDragan**
Most changes are denoted with a comment giving the reasoning. Feel free to ask me about any of the changes. For the change to the buy item function you need a new snip as well as the loss check. I haven't figured out how to suggest images as a patch yet so that'll need to be done here at some point.

### CODE REVIEW

**Comment by PsychoticDragan** [comment]
On a side note, buy item is useless in general terms as it will automatically pick one by the middle of the round.

**Comment by PsychoticDragan** [comment]
I added copies of all champs in respective folders. This doesn't need to be pushed over but I thought I'd add them since I had them. Some of them might be outdated in the sense that they're no longer in tft. Like coven? I think. I did add tristana, dead, loading, choose one, and 6-6 which were in my code. Those are the only ones that are needed I believe.

**Comment by Detergent13** [comment]
Hey- sorry for my absence, things have been crazy recently! Looks good on first glance, I'll test more thoroughly soon and hopefully merge. Thank you for your contribution!

**Comment by lencuteprovip** [comment]
hello, can you help me install this?

**Comment by lencuteprovip** [comment]
if you can, pls record videos for me, thank you very much

**Comment by RandomClaim** [comment]
I've tried to run your branch but ran into an issue. Directly after the bot queues up for a game, I receive the following error message after which the program exits:

```python
Welcome! You're running Detergent's TFT bot.
Please feel free to ask questions or contribute at https://github.com/Detergent13/tft-bot
Bot started, queuing up!
Traceback (most recent call last):
  File "E:\tft-bot-patched\tft-bot\tft.py", line 203, in <module>
    queue()
  File "E:\tft-bot-patched\tft-bot\tft.py", line 67, in queue
    while not onscreen("./captures/loading.png"):
  File "E:\tft-bot-patched\tft-bot\tft.py", line 24, in onscreen
    return search(path, precision)[0] != -1
  File "C:\tools\miniconda3\lib\site-packages\python_imagesearch\imagesearch.py", line 122, in imagesearch
    template.shape[::-1]
AttributeError: 'NoneType' object has no attribute 'shape'
```

Any idea what could be the cause of this?

@PsychoticDragan

**Comment by PsychoticDragan** [comment]
@RandomClaim It seems that i had a typo in this code. Go to the line 97 there's a / missing in front of poppy. I fixed it here so you can either just navigate to that line of code and add it in your copy or re-download the tft.py.

**Comment by lencuteprovip** [comment]
Can you pls Teamviewer and help me with that? :<

Vào 2:11 SA, CN, 15 thg 8, 2021 PsychoticDragan ***@***.***>
đã viết:

**Comment by RandomClaim** [comment]
@PsychoticDragan After Pulling I still got the issue. However, I've just now noticed that you have 2 branches in your fork and  I was puling from main. It seems that at least  in the main branch you have some errors due to the file structure:
Three Images (`choose_one.PNG`, `dead.PNG` and `loading.PNG`) were located at the repos root folder but your code expects them to be inside `./captures/`. 

Anyways, using the other branch `patch-2` worked for me.

**Comment by PsychoticDragan** [comment]
I wasn't pushing to the main. The one I was updating and set up the pull
request with(the thing your commenting on) is for patch-2 atleast it should
be.

**Comment by RandomClaim** [comment]
Yea sorry I did not notice that at first.

**Comment by Detergent13** [comment]
Thank you for your contribution! Sorry for going MIA on you, but I appreciate your help <3

**Comment by PsychoticDragan** [comment]
Hey, no worries.  Life comes when it wants to and there's no way to stop
that train if you have a ticket.

**Pull request merged**
