### PR TITLE
update + experimental gold decisions

### PR DESCRIPTION
**Pull request by RomeoAlphaEkko**
**updates:**
- dragon - wont reroll anymore (pro saves gold / con no automatic mission anymore
- xp - will now buy xp -> Enhancement: “Buy XP” #75
- death - icon play till 0 hp
- new 1-1 carussel position -- item collection didnt work before
- screenshot for ok button

**experimental:**
- gold based decisions -> feels like the image recognition has problems -> https://github.com/Detergent13/tft-bot/issues/76
- only low based gold values aka dont click if you have no gold

### CODE REVIEW

**Comment by Detergent13** [comment]
This looks super cool but I really don't have the time to do proper testing for it. If anybody has tried it out, please let me know how the stability is!

Also I would rather not have the experimental features (gold related) in the main branch, I'd be willing to make an experimental branch if you want though? I think stability is one of the most important things, especially for something that you'd expect to run in the background for even days at a time.

I'm generally against adding too many bells and whistles for that reason, but the non-experimental changes seem very reasonable to merge.

Thank you again for your contributions!

**Comment by RomeoAlphaEkko** [comment]
Hi,
it runs stable, you. (that is tested)

the main point would be like over"blocking" the wrong recognition, 9 and sometimes 8 gets seen as 0
and sometimes it still rerolls even though it should not (having enough gold to reroll but not enough to use the shop afterwards)

**Comment by RomeoAlphaEkko** [comment]
@kyrluckechuck
as you use different versions if trying it out, will it break this version? aka update requirements

**Comment by Kyrluckechuck** [comment]
@RomeoAlphaEkko 
As long as you run a `pip install -r requirements.txt` before running either this branch or my branch, the requirements shouldn't break?

But in terms of compatibility, this branch/code will likely not merge/rebase cleanly with the changes I made since I've overhauled nearly the entire repo -- no worries though for now since I don't want to merge my fork upstream unless @Detergent13 decides they want that, again since it's nearly an entire rewrite and fairly decently more complicated than this in both in terms of code complexity and functionality

**Comment by Detergent13** [comment]
If you want to use these changes, please check out @Kyrluckechuck's fork at https://github.com/Kyrluckechuck/TFT-Bot! It's orders of magnitude more feature-rich than my original.

**Pull request closed without merging**
