### PR TITLE
Update playtime,gamecount

### PR DESCRIPTION
**Pull request by CaS1ow**
Please check the code

### CODE REVIEW

**Comment by Detergent13** [comment]
Hey! Looks like a good addition, I'll test it myself and get back to you

**Comment by Detergent13** [comment]
Upon testing it seems to be pretty inconsistent on if/when it prints the time after games; i.e. it will go through a few game cycles without printing, or flip-flop the printing order. Has anybody else experienced this or have an idea of why this could be?

**Comment by CaS1ow** [comment]
> Upon testing it seems to be pretty inconsistent on if/when it prints the time after games; i.e. it will go through a few game cycles without printing, or flip-flop the printing order. Has anybody else experienced this or have an idea of why this could be?

I've never experienced that before.
the "start timer" start when def queue():  started and then the "end timer" start at def won_match():
In my case, it works well. thats weird..

**Comment by Detergent13** [comment]
I'll continue testing, I agree that it's a weird issue. It seems like it tends to happen after the script has been running for quite a while (like mine often is), although this could just be a coincidence.

**Comment by CaS1ow** [comment]
> I'll continue testing, I agree that it's a weird issue. It seems like it tends to happen after the script has been running for quite a while (like mine often is), although this could just be a coincidence.

try to start timer after detect 1-1 or something else place :D

**Comment by Detergent13** [comment]
It seems like this is an issue with the existing code, since the current match end text is a bit inconsistent. As this is a pre-existing issue with my own code, I see no problem with merging your work! Thank you for your contribution!

**Pull request merged**
