### PR TITLE
Set 7 PBE (working) + Fixed game counter

### PR DESCRIPTION
**Pull request by Raenef**
a working version on the PBE for set 7 being released in a few days + a fix for the game counter which was missing in the correct method

### CODE REVIEW

**Comment by Detergent13** [comment]
Looks good, thanks for doing my work for me! I just put that code under a method since it's now used in multiple places, but otherwise perfect.

**Comment by Dazlian** [comment]
Hi, can you do the same for the new set?

**Comment by Raenef** [comment]
> 

u mean working version for the new set?

**Comment by Dazlian** [comment]
Yes

**Comment by Raenef** [comment]
i hope i have done the pull request right then it should be up soon, still new to gh

**Pull request merged**
