### PR TITLE
Update tft.py

### PR DESCRIPTION
**Pull request by hyp0711**

### CODE REVIEW

**Comment by RomeoAlphaEkko** [comment]
This is the third or fourth time he is doing this

**Comment by Detergent13** [comment]
@hyp0711 this is the third time you've made the same useless PR. Both other times, I closed it and explained why this shouldn't be done. I'm assuming it's by accident, but please stop.

Pull requests are a request to modify the main code. They're not necessary for just configuring something like the surrender stage for yourself.

Please confirm that you understand this.

**Comment by hyp0711** [comment]
I'm sorry. I didn't mean to make a noise. I just want to download the file that I modified, but I don't know how to download it, so I'm trying to press this and that. I'm sorry again if I disturbed you.

**Comment by RomeoAlphaEkko** [comment]
You download the file, go to the download folder, right click it, open, edit , safe it, then run it

**Comment by Detergent13** [comment]
No problem. @RomeoAlphaEkko offers a good solution; just download and edit it locally

**Pull request closed without merging**
